# Project-wide Gradle settings.

# Memory Allocation for Gradle Build Process
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Kotlin Code Style
kotlin.code.style=official

# Non-transitive R classes for build speed
android.nonTransitiveRClass=true